### ISSUE TITLE
'Sender': see if anyone is going to desired destination

### ISSUE THREAD

**Issue by mk4111** [ayooo-team/prototype#3] opened 2016-03-21 18:22 UTC
As a user, I want to be able to see if there is anyone to take my package to my desired destination.
- [ ] Display travellers and their journey details.
- [ ] Journey details will include: name of traveller, proposed date of travel, destination of travel, size of package that can be carried, etc.
- [ ] A button to request a traveller for their service.

**Comment by iteles** [comment] 2016-03-21 18:40
You don't need to put the whole user story into the issue title, just the useful information :blush: 

e.g. Here you could have 'Check if courier is en route to my desired destination'
And then the first thing in the issue is your full user story followed by the checklist you have here (which is great by the way!)

**Comment by mk4111** [comment] 2016-03-21 21:56
@iteles oooh! Thank you for telling me!! Roger that!! I'll be sure to fix them up tomorrow morning!! :D

**Comment by iteles** [comment] 2016-03-21 22:08
Just helps facilitate the scanning of the issue list if all the titles fit within the screen :relaxed:

**Comment by minaorangina** [comment] 2016-03-25 19:04
As of meeting on 24/03, this will no longer be the case for MVP.  Instead, Paolo will manually match senders with travellers

**Comment by minaorangina** [comment] 2016-03-25 19:05
if @mk4111 and @PAOLOPRIAMODAMU agree, will close this issue?

**Comment by mk4111** [comment] 2016-03-25 22:04
@minaorangina yes I agree.

**Closed as completed** 2016-04-26 19:27 UTC
Labels: question
